### ISSUE TITLE
Different tasks

### ISSUE THREAD

**Issue by iezhanqingran** [JRMeyer/multi-task-kaldi#1]
Hi,
Thanks for you good project!
What I'm doing now is mutistask, but on task is normal asr and others are classification task.
So for the classification tasks, should I use get_egs_targets.sh  and for asr task use get_egs.sh to get the egs and combine them together? and which training script should I use? train_dnn.py or train_raw_dnn.py?
Thanks a lot

**Comment by JRMeyer** [comment]
Hi there,

I need some more specific information before I can answer your question... what kind of "classification task" are you wanting to do?

**Comment by iezhanqingran** [comment]
> Hi there,
> 
> I need some more specific information before I can answer your question... what kind of "classification task" are you wanting to do?

Thanks for your reply!
For the classification task, It is a simple classifier. For example, the input is mfcc, and the data has four classes, the label is like: 1000. 0100, 0010, 0001.

**Comment by JRMeyer** [comment]
Then you're going to have to crack open the `Nnet3Egs` files... I've done this in the following repo:

https://github.com/JRMeyer/kaldi-tf#modifying-kaldi-egs

**Comment by iezhanqingran** [comment]
Thanks! I think my problems are the multi-task not multiligual, so every input has more than one label.
I'll look at this repo! Thanks.

**Comment by JRMeyer** [comment]
in this repo, multi-task and multilingual are synonymous, where a new language is framed as a new task

good luck!
