### ISSUE TITLE
Hi, I've been learning to multitask in speech recognition，Here's my question

### ISSUE THREAD

**Issue by aikekeaishenghuo** [JRMeyer/multi-task-kaldi#2]
I don't understand the following operation：
“ steps/nnet3/train_raw_dnn.py \
        --stage=-5 \
        --cmd="$cmd" \
        --trainer.num-epochs $num_epochs \
        --trainer.optimization.num-jobs-initial=1 \
        --trainer.optimization.num-jobs-final=1 \
        --trainer.optimization.initial-effective-lrate=0.0015 \
        --trainer.optimization.final-effective-lrate=0.00015 \
        --trainer.optimization.minibatch-size=256,128 \
        --trainer.samples-per-iter=10000 \
        --trainer.max-param-change=2.0 \
        --trainer.srand=0 \
        --feat.cmvn-opts="--norm-means=false --norm-vars=false" \
        --feat-dir ${multi_data_dirs[0]} \
        --egs.dir $master_egs_dir \
        --use-dense-targets false \
        --targets-scp ${multi_ali_dirs[0]} \
        --cleanup.remove-egs true \
        --use-gpu true \
        --dir=$exp_dir  \
        || exit 1;
”
ERROR (nnet3-compute-prob[5.5.172~1-1079]:ProcessOutputs():nnet-diagnostics.cc:110) Nnet versus example output dimension (num-classes) mismatch for 'output-0': 2944 (nnet) vs. 2952 (egs)

What are the specific problems

**Comment by JRMeyer** [comment]
there's a mis-match in the number of output classes (i.e. phoneme-ids)

**Comment by aikekeaishenghuo** [comment]
> there's a mis-match in the number of output classes (i.e. phoneme-ids)

I have two tasks, one with an output of 2944 and one with an output of 2952；You mean the output of both tasks must be Or what does it mean

**Comment by JRMeyer** [comment]
your examples (egs) have a dimension of `2952`, but your task (`output-0`, aka your first task) expects a dimensionality of `2944`... so either your task is looking at the wrong examples (i.e. task1 is looking at task2 examples) or your examples for task1 are not correctly formatted

what are your tasks?

**Comment by aikekeaishenghuo** [comment]
> your examples (egs) have a dimension of``2952`, but your task (`output-0`, aka your first task) expects a dimensionality of `2944`... so either your task is looking at the wrong examples (i.e. task1 is looking at task2 examples) or your examples for task1 are not correctly formatted
> 
> what are your tasks?

One is 8k speech recognition task, one is 16k speech recognition task (sample rate)   But I found that the audio files for both tasks have the same name, which may be the problem
Do you have any Suggestions for these two tasks

**Comment by JRMeyer** [comment]
I don't think it should be a problem if the audio has same-named WAV files... the code should take care of that (I ran into that problem before)

Have you made any changes to the code?

**Comment by JRMeyer** [comment]
I'm surprised you're not getting errors about the sampling rates being different, though...

**Comment by aikekeaishenghuo** [comment]
> I don't think it should be a problem if the audio has same-named WAV files... the code should take care of that (I ran into that problem before)
> 
> Have you made any changes to the code?




> I don't think it should be a problem if the audio has same-named WAV files... the code should take care of that (I ran into that problem before)
> 
> Have you made any changes to the code?

no ， I didn't make any changes.

**Comment by aikekeaishenghuo** [comment]
> I'm surprised you're not getting errors about the sampling rates being different, though...

**Comment by aikekeaishenghuo** [comment]
> I don't think it should be a problem if the audio has same-named WAV files... the code should take care of that (I ran into that problem before)
> 
> Have you made any changes to the code?

For multitasking, what experiments have you tried? Can you briefly introduce them? I'm trying different sampling rates as different tasks, I don't know what the final result will be.

**Comment by JRMeyer** [comment]
did you solve the issue? can you let us know how you fixed it?

You can read about the experiments I've done in chapters 5/6/7 of my dissertation: http://jrmeyer.github.io/misc/MEYER_dissertation_2019.pdf

**Comment by aikekeaishenghuo** [comment]
That problem hasn't been solved, but if you don't re-read the wav file names for both tasks, that's fine.

This is what I ended up doing when I was working on the problem：
Error in RandomAccessTableReader: duplicate key sp1.1-BAC009S0075W0470-62 in archive /data/chunwei.gong/kaldi/egs/multi-task-kaldi-master/mtk/20190923//exp/nnet3/multitask/egs/train_diagnostic.weight.ark
Now I'm looking at the script, what happens to the audio file with the same name
